"""Flood mutations with intake enrichment + matrix maintenance (Phase 1.5).

Adding/editing/deleting a flood keeps floods.csv AND the scenario's OSRM
matrices consistent: a new point is enriched (road_class + dist_faskes) and its
row/col spliced into the matrices, so the point is usable immediately without a
full rebuild. Node order matches instance.py: [depots, floods, ifs].
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd
from fastapi import HTTPException

from app.config import scenario_floods_path, scenario_matrix_paths
from app.data.store import store
from app.preprocessing import enrich, workload
from app.preprocessing import matrix as mx


def _node_coords(depots, floods, ifs) -> tuple[np.ndarray, np.ndarray]:
    lats = np.concatenate([depots["lat"], floods["lat"], ifs["lat"]]).astype(float)
    lons = np.concatenate([depots["lon"], floods["lon"], ifs["lon"]]).astype(float)
    return lats, lons


def _save_matrices(sid: str, dist: np.ndarray, time: np.ndarray) -> None:
    dpath, tpath = scenario_matrix_paths(sid)
    np.save(dpath, dist)
    np.save(tpath, time)


def _write_floods(sid: str, floods: pd.DataFrame) -> None:
    # `id` is regenerated by load_floods from row order; don't persist it.
    floods.drop(columns=["id"], errors="ignore").to_csv(scenario_floods_path(sid), index=False)


def _workload_l(depth_cm: Any, time_to_ifs: np.ndarray | None, ifs: pd.DataFrame) -> float:
    """Expected pumping workload for an intake point.

    A point reported right now has no recorded duration, so it draws the
    expected on-scene time for its depth class from the calibrated log.
    """
    depth = pd.to_numeric(depth_cm, errors="coerce")
    cycle = (
        workload.if_cycle_seconds(
            time_to_ifs, ifs.get("waterway_type", pd.Series([""] * len(ifs))).tolist()
        )
        if time_to_ifs is not None and len(time_to_ifs)
        else workload.FALLBACK_CYCLE_S
    )
    on_scene = workload.expected_on_scene_s(
        float(depth) if pd.notna(depth) else None, list(workload.default_table())
    )
    return round(workload.volume_liters(on_scene, cycle), 1)


def _row_index(floods: pd.DataFrame, flood_id: str) -> int:
    idxs = floods.index[floods["id"] == flood_id].tolist()
    if not idxs:
        raise HTTPException(status_code=404, detail=f"flood id='{flood_id}' tidak ditemukan.")
    return int(idxs[0])


def add_flood(sid: str, payload: dict[str, Any]) -> dict[str, Any]:
    b = store.get(sid)
    floods = b.floods
    row: dict[str, Any] = {"id": f"F_{len(floods):04d}", **payload}

    lat, lon = payload.get("lat"), payload.get("lon")
    if lat is not None and lon is not None:
        rc, dfk = enrich.enrich_attrs(float(lat), float(lon), faskes_df=b.faskes)
        row.setdefault("road_class", rc)
        row.setdefault("dist_faskes_m", dfk)

        time_to_ifs = None
        if b.distance_matrix is not None:
            lats, lons = _node_coords(b.depots, floods, b.ifs)  # old nodes
            rd, cd, rt, ct = enrich.node_vectors(float(lat), float(lon), lats, lons)
            pos = len(b.depots) + len(floods)  # new flood at end of floods block
            time_to_ifs = rt[pos:]
            _save_matrices(
                sid,
                mx.insert_node(b.distance_matrix, pos, rd, cd),
                mx.insert_node(b.time_matrix, pos, rt, ct),
            )

        row.setdefault(
            "volume_l", _workload_l(row.get("ketinggian_cm"), time_to_ifs, b.ifs)
        )

    _write_floods(sid, pd.concat([floods, pd.DataFrame([row])], ignore_index=True))
    store.invalidate(sid)
    return row


def update_flood(sid: str, flood_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    b = store.get(sid)
    floods = b.floods.copy()
    i = _row_index(floods, flood_id)

    updates = {k: v for k, v in payload.items() if v is not None}
    coords_changed = "lat" in updates or "lon" in updates
    for k, v in updates.items():
        floods.at[i, k] = v

    lat = float(floods.at[i, "lat"])
    lon = float(floods.at[i, "lon"])
    time_to_ifs = None
    if coords_changed:
        rc, dfk = enrich.enrich_attrs(lat, lon, faskes_df=b.faskes)
        floods.at[i, "road_class"] = rc
        floods.at[i, "dist_faskes_m"] = dfk

        if b.distance_matrix is not None:
            lats, lons = _node_coords(b.depots, b.floods, b.ifs)
            rd, cd, rt, ct = enrich.node_vectors(lat, lon, lats, lons)
            pos = len(b.depots) + i
            time_to_ifs = rt[len(b.depots) + len(b.floods):]
            _save_matrices(
                sid,
                mx.replace_node(b.distance_matrix, pos, rd, cd),
                mx.replace_node(b.time_matrix, pos, rt, ct),
            )

    if coords_changed or "ketinggian_cm" in updates:
        if "volume_l" not in floods.columns:
            floods["volume_l"] = np.nan
        floods.at[i, "volume_l"] = _workload_l(
            floods.at[i, "ketinggian_cm"], time_to_ifs, b.ifs
        )

    _write_floods(sid, floods)
    store.invalidate(sid)
    return {c: floods.at[i, c] for c in floods.columns}


def delete_flood(sid: str, flood_id: str) -> None:
    b = store.get(sid)
    floods = b.floods
    i = _row_index(floods, flood_id)

    if b.distance_matrix is not None:
        pos = len(b.depots) + i
        _save_matrices(
            sid, mx.remove_node(b.distance_matrix, pos), mx.remove_node(b.time_matrix, pos)
        )

    _write_floods(sid, floods.drop(i).reset_index(drop=True))
    store.invalidate(sid)
